/**
 * Relies on pre-processed JSON files in the `data` directory
 * Generated by `scripts/update-data.ts` and derived from the
 * crosswalk.csv available in the CodeMeta GitHub repository.
 */

import is from '@sindresorhus/is'
import crosswalkDocument from './data/crosswalk.json' with { type: 'json' }

export const crosswalk = crosswalkDocument
export type Crosswalk = typeof crosswalk
export type CrosswalkSourceKey = keyof Crosswalk['maps']
type CrosswalkTypeKey = keyof Crosswalk['types']

/**
 * Type guard to check if a string is a valid type key.
 */
export function isCrosswalkTypeKey(value: unknown): value is CrosswalkTypeKey {
	return is.string(value) && value in crosswalk.types
}

/**
 * Parent types that represent the subject node itself (SoftwareSourceCode).
 * Properties with these parent types are added directly to the subject.
 * Properties with other parent types (e.g. schema:Person) belong on sub-nodes.
 */
export const SUBJECT_PARENT_TYPES = new Set([
	'codemeta:SoftwareSourceCode',
	'schema:CreativeWork',
	'schema:SoftwareApplication',
	'schema:SoftwareSourceCode',
	'schema:Thing',
])

/**
 * Parse a prefixed crosswalk key like "schema:Person/email" into its parts.
 */
export function parseCrosswalkKey(
	key: string,
): undefined | { parentType: string; property: string } {
	const slashIndex = key.indexOf('/')
	if (slashIndex === -1) return undefined
	return {
		parentType: key.slice(0, slashIndex),
		property: key.slice(slashIndex + 1),
	}
}
